### ISSUE TITLE
UTF Icons don't show up in HTML report

### ISSUE THREAD

**Issue by Animesh-Ghosh** [Bhupesh-V/areyouok#1]
**Describe the bug**
UTF icons don't show up in the generated HTML report.

**To Reproduce**
1. Run the binary
2. Serve the generated HTML report.
3. No fancy icons 😢 

**Expected behavior**
Need muh UTF icons.

**Screenshots**
![image](https://user-images.githubusercontent.com/34956994/105629843-69888b80-5e6b-11eb-9d00-6a4df49acab4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by Bhupesh-V** [comment]
Hey @Animesh-Ghosh Thanks a lot for reporting this
Can you check if https://github.com/Bhupesh-V/areyouok/releases/tag/v1.1.0 fixes this?

**Comment by Animesh-Ghosh** [comment]
Yes, seems fine! Updated the [bucket](https://github.com/Animesh-Ghosh/kulfi-scoop) as well.
![image](https://user-images.githubusercontent.com/34956994/105840176-97e7a180-5ff8-11eb-9290-5ed569ab6d4f.png)

**Comment by Bhupesh-V** [comment]
@all-contributors please add @Animesh-Ghosh for bug
